replicaCount: 1

image:
  repository: mwikiacr.azurecr.io/test/mariadb-image-isha
  pullPolicy: IfNotPresent
  tag: "latest1"
imagePullSecrets: 
- name: acrimagepull 

MYSQL_ROOT_PASSWORD: jhgygkbiwwkipmkl
MYSQL_PASSWORD: vhjlkiunhu
MYSQL_DATABASE: mediawikidb
MYSQL_USER: wikiuser

service:
  type: ClusterIP
  port: 3306
  targetport: 3306


resources: {}
